#!/usr/bin/env python
import sys
import gtk
from smithwidget import SmithWidget
import components
from transform import gamma_to_z
import spicenum

class SmithWindow(gtk.Window):
    def __init__(self):
        gtk.Window.__init__(self)
        self.set_title("Interactive Smith Chart")
        self.set_default_size(600, 600)
        self.smith = SmithWidget()
	self.add(self.smith)
	self.smith.grab_default()
	self.smith.grab_focus()

        self.smith.connect("key_press_event", self._smith_key_press_event)
        self.smith.connect("button_press_event", self._smith_click_event)

        self.cindex = 0
        self.smith.component = components.types[self.cindex]()
        self.smith.component.connect("notify::normval", self.component_value_changed)

    def _smith_key_press_event(self, w, event):
        key = gtk.gdk.keyval_name(event.keyval)
        if key == 'space':
            self.cindex = (self.cindex + 1) % len(components.types)
            del self.smith.component
            self.smith.component = components.types[self.cindex]()
            self.smith.component.connect("notify::normval", self.component_value_changed)
        elif key == 'Escape':
            del self.smith.component
            self.smith.component = None
            self.smith.queue_draw()
            print "\x1b[K",
            sys.stdout.flush()
        else:
            print "Key event: ", key

    def _smith_click_event(self, w, event):
	gamma = self.smith.xy_to_gamma(event.x, event.y)
	z = gamma_to_z(gamma)
	if self.smith.load is None or event.state & gtk.gdk.SHIFT_MASK:
            self.smith.set_load(z)
            return
        if self.smith.load is not None and self.smith.component is not None:
            self.smith.solution.push_component(self.smith.component)
            self.smith.component = components.types[self.cindex]()
            self.smith.component.connect("notify::normval", self.component_value_changed)
            print

    def component_value_changed(self, component, paramstring):
        print ("%s: %s   \r" % (component.format_type(),
                                component.format_physval(50, 2.4e9))),
        sys.stdout.flush();

def main():
    w = SmithWindow()
    w.connect("destroy", gtk.main_quit)
    w.show_all()
    gtk.main()

if __name__ == "__main__":
    main()

